name: flutter_ecommerce
description: "A new Flutter application."


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: "3.4.0-282.2.beta"


dependencies:
  flutter:
    sdk: flutter


  # Utility packages
  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.1.0
  lottie: ^2.7.0
  shimmer: ^3.0.0
  image_picker: ^1.0.4
  cached_network_image: ^3.1.0
  url_launcher: ^6.2.5
  pdf: ^3.1.0
  flutter_pdfview: ^1.3.2
  path_provider: ^2.0.14
  connectivity_plus: ^5.0.1
  carousel_slider: ^4.2.1
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0
  readmore: ^3.0.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.6

  # State management
  get: ^4.6.6
  get_storage: ^2.1.1
  firebase_core: ^2.29.0
  firebase_storage: ^11.5.4

  # Firebase
  firebase_auth: ^4.19.2
  cloud_firestore: ^4.17.0
  google_sign_in: ^6.1.6


  flutter_rating_bar: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  #----------Local assets-----------#
  assets:
    - assets/logos/
    - assets/images/user/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/icons/categories/
    - assets/images/banners/
    - assets/images/products/
    - assets/icons/payment_methods/
    - assets/pdf/

  #----------Local font------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800