// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr701oaP_kPvNJw4f8GPcE20FQ7X7KBUs',
    appId: '1:267802890519:web:7508adf886e64a684c6752',
    messagingSenderId: '267802890519',
    projectId: 'ecommerceflutter-75a47',
    authDomain: 'ecommerceflutter-75a47.firebaseapp.com',
    storageBucket: 'ecommerceflutter-75a47.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiLoefVulsbvKonX-tIUwnwnsA_FawxhE',
    appId: '1:267802890519:android:8b91486e81e1db494c6752',
    messagingSenderId: '267802890519',
    projectId: 'ecommerceflutter-75a47',
    storageBucket: 'ecommerceflutter-75a47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLZx3eZ5bLCtLBHnCU3JAZlXr22ZApYU8',
    appId: '1:267802890519:ios:af86cd58f0ee68ad4c6752',
    messagingSenderId: '267802890519',
    projectId: 'ecommerceflutter-75a47',
    storageBucket: 'ecommerceflutter-75a47.appspot.com',
    iosClientId: '267802890519-7i095r3t4o16vum735qe0foc2ieev7pq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLZx3eZ5bLCtLBHnCU3JAZlXr22ZApYU8',
    appId: '1:267802890519:ios:af86cd58f0ee68ad4c6752',
    messagingSenderId: '267802890519',
    projectId: 'ecommerceflutter-75a47',
    storageBucket: 'ecommerceflutter-75a47.appspot.com',
    iosClientId: '267802890519-7i095r3t4o16vum735qe0foc2ieev7pq.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterEcommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr701oaP_kPvNJw4f8GPcE20FQ7X7KBUs',
    appId: '1:267802890519:web:808f0720d25d452e4c6752',
    messagingSenderId: '267802890519',
    projectId: 'ecommerceflutter-75a47',
    authDomain: 'ecommerceflutter-75a47.firebaseapp.com',
    storageBucket: 'ecommerceflutter-75a47.appspot.com',
  );

}